//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class order
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int cart_id { get; set; }
        public int address_id { get; set; }
        public string payment_type { get; set; }
        public string order_status { get; set; }
    
        public virtual address address { get; set; }
        public virtual cart cart { get; set; }
        public virtual user user { get; set; }
    }
}
